import './globals.tail.css'
import NavBar from '@/components/ui/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className='bg-gradient-to-tr from-slate-50 via-slate-200 to-neutral-200'>
        {/* <main className="p-4 py-24 gap-6 w-full lg:w-[55%] bg-purple-400"> */}
        <NavBar />
        {children}
        {/* </main> */}
      </body>
    </html>
  )
}
